# Complete OpenVPN configuration with embedded certificates
output "complete_ovpn_config" {
  description = "Complete OpenVPN configuration file with embedded certificates"
  sensitive   = true
  value = <<-EOT
# Cashabl VPN Configuration - Generated by Terraform
client
dev tun
proto udp
remote ${aws_ec2_client_vpn_endpoint.this.dns_name} 443
resolv-retry infinite
nobind
remote-random-hostname
remote-cert-tls server
cipher AES-256-GCM
verb 3

<ca>
${tls_self_signed_cert.ca.cert_pem}</ca>

<cert>
${tls_locally_signed_cert.client.cert_pem}</cert>

<key>
${tls_private_key.client.private_key_pem}</key>

reneg-sec 0
EOT
}
